using System.Text;
using LibraryAPI.Data;
using LibraryAPI.Services;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;

// ─────────────────────────────────────────────────────────────────────────────
// Program.cs — Application Entry Point
// Configures the DI container, middleware pipeline, and starts the server.
// ─────────────────────────────────────────────────────────────────────────────

var builder = WebApplication.CreateBuilder(args);

// ── 1. MVC Controllers ────────────────────────────────────────────────────────
builder.Services.AddControllers();

// ── 2. SQLite Database via Entity Framework Core ──────────────────────────────
// Connection string is defined in appsettings.json
// The SQLite file (library.db) is created in the project root
builder.Services.AddDbContext<LibraryDbContext>(options =>
    options
        .UseSqlite(builder.Configuration.GetConnectionString("DefaultConnection"))
        // EF Core 9 raises PendingModelChangesWarning as an error when the snapshot
        // was generated by a different EF Core version. Safe to suppress here since
        // the schema is correct — we just crossed from EF Core 8 to 9 packages.
        .ConfigureWarnings(w => w.Ignore(
            Microsoft.EntityFrameworkCore.Diagnostics.RelationalEventId.PendingModelChangesWarning)));

// ── 3. Register Application Services (Dependency Injection) ───────────────────
// Scoped = one instance per HTTP request (appropriate for DB-backed services)
builder.Services.AddScoped<IBookService, BookService>();
builder.Services.AddScoped<IAuthService, AuthService>();

// ── 4. JWT Authentication ─────────────────────────────────────────────────────
string jwtKey = builder.Configuration["Jwt:Key"]
    ?? throw new InvalidOperationException("JWT Key is not configured in appsettings.json");

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = builder.Configuration["Jwt:Issuer"],
            ValidAudience = builder.Configuration["Jwt:Audience"],
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey))
        };
    });

builder.Services.AddAuthorization();

// ── 5. CORS — Allow React frontend to call the API ────────────────────────────
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowFrontend", policy =>
    {
        policy
            .WithOrigins(
                "http://localhost:5173",  // Vite default
                "http://localhost:3000"   // Alt dev port
            )
            .AllowAnyHeader()
            .AllowAnyMethod();
    });
});

// ── 6. Swagger / OpenAPI Documentation ───────────────────────────────────────
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new OpenApiInfo
    {
        Title = "Library Management API",
        Version = "v1",
        Description = "RESTful API for managing library book records. Built with C# .NET 8, Entity Framework Core, and SQLite.",
        Contact = new OpenApiContact
        {
            Name = "Library System",
            Email = "admin@library.com"
        }
    });

    // Add JWT authentication support in Swagger UI
    options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Name = "Authorization",
        Type = SecuritySchemeType.Http,
        Scheme = "Bearer",
        BearerFormat = "JWT",
        In = ParameterLocation.Header,
        Description = "Enter your JWT token. Example: Bearer eyJhbGci..."
    });

    options.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "Bearer" }
            },
            Array.Empty<string>()
        }
    });
});

// ── Build the application ──────────────────────────────────────────────────────
var app = builder.Build();

// ── 7. Ensure Database Schema Exists ────────────────────────────────────────
// EnsureCreated() creates all tables directly from the EF Core model if they
// do not exist yet — no migration history required. This is equivalent to
// running migrations for a fresh database and works reliably across EF versions.
// Seed data defined via HasData() in LibraryDbContext is also applied here.
using (var scope = app.Services.CreateScope())
{
    var dbContext = scope.ServiceProvider.GetRequiredService<LibraryDbContext>();
    dbContext.Database.EnsureCreated(); // Creates DB schema from model + seeds
}

// ── 8. Middleware Pipeline ────────────────────────────────────────────────────
// Swagger enabled unconditionally so it's accessible in both Development
// and Production modes (useful during assignment demo/testing)
app.UseSwagger();
app.UseSwaggerUI(options =>
{
    options.SwaggerEndpoint("/swagger/v1/swagger.json", "Library API v1");
    options.RoutePrefix = "swagger"; // Access via /swagger
});

app.UseCors("AllowFrontend");       // Must be before Authentication/Authorization
app.UseHttpsRedirection();
app.UseAuthentication();            // JWT token validation
app.UseAuthorization();             // Role-based access control
app.MapControllers();               // Map all [ApiController] routes

app.Run();
