// <auto-generated />
// EF Core 9.0 Model Snapshot — targeting net10.0
using System;
using LibraryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryAPI.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("LibraryAPI.Models.Book", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Author").IsRequired().HasMaxLength(150).HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("Description").HasMaxLength(2000).HasColumnType("TEXT");
                b.Property<string>("Genre").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("ISBN").HasMaxLength(20).HasColumnType("TEXT");
                b.Property<int?>("PublishedYear").HasColumnType("INTEGER");
                b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("Author");
                b.HasIndex("ISBN").IsUnique().HasFilter("[ISBN] IS NOT NULL");
                b.HasIndex("Title");
                b.ToTable("Books");
                b.HasData(
                    new { Id = 1, Author = "Robert C. Martin", CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), Description = "A handbook of agile software craftsmanship.", Genre = "Technology", ISBN = "978-0132350884", PublishedYear = 2008, Title = "Clean Code", UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 2, Author = "Andrew Hunt & David Thomas", CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), Description = "From journeyman to master.", Genre = "Technology", ISBN = "978-0135957059", PublishedYear = 1999, Title = "The Pragmatic Programmer", UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 3, Author = "Gang of Four", CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), Description = "Elements of reusable object-oriented software.", Genre = "Technology", ISBN = "978-0201633610", PublishedYear = 1994, Title = "Design Patterns", UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc) });
            });

            modelBuilder.Entity("LibraryAPI.Models.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Role").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.Property<string>("Username").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.HasIndex("Username").IsUnique();
                b.ToTable("Users");
            });
#pragma warning restore 612, 618
        }
    }
}
